# Generated by Django 5.2.15 on 2026-07-22 22:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformStaffAuth",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("totp_secret_encrypted", models.TextField(blank=True, null=True)),
                ("totp_enrolled_at", models.DateTimeField(blank=True, null=True)),
                ("recovery_code_hashes", models.JSONField(default=list)),
                ("recovery_generated_at", models.DateTimeField(blank=True, null=True)),
                ("failed_attempts", models.PositiveSmallIntegerField(default=0)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_auth",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform staff auth",
                "verbose_name_plural": "Platform staff auth",
                "db_table": "platform_staff_auth",
            },
        ),
    ]
