# Generated by Django 5.2.15 on 2026-07-24 18:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_admin_app", "0002_adminsession"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "actor_label",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("action", models.CharField(db_index=True, max_length=100)),
                (
                    "resource_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "resource_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "restaurant_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("delegation_id", models.UUIDField(blank=True, null=True)),
                ("reason", models.TextField(blank=True, default="")),
                ("before_state", models.JSONField(blank=True, null=True)),
                ("after_state", models.JSONField(blank=True, null=True)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("success", "success"),
                            ("failure", "failure"),
                            ("denied", "denied"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "error_code",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "request_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("source_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admin_audit_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_entries",
                        to="platform_admin_app.adminsession",
                    ),
                ),
            ],
            options={
                "db_table": "admin_audit_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["restaurant_id", "created_at"],
                        name="admin_audit_restaur_f83456_idx",
                    ),
                    models.Index(
                        fields=["actor", "created_at"],
                        name="admin_audit_actor_i_a86fdb_idx",
                    ),
                ],
            },
        ),
    ]
