# Generated by Django 5.2.15 on 2026-07-24 22:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_admin_app", "0004_platformstaffauth_last_totp_counter_and_more"),
        ("restaurants_app", "0055_sanitize_menu_item_extras"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DelegationGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("view", "view"), ("support", "support")],
                        max_length=16,
                    ),
                ),
                ("reason", models.TextField()),
                ("exchange_code_hash", models.CharField(max_length=64, unique=True)),
                ("code_expires_at", models.DateTimeField()),
                ("session_ttl_seconds", models.PositiveIntegerField(default=900)),
                ("issued_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("redeemed_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "revoked_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("issued_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("issued_user_agent", models.TextField(blank=True, default="")),
                (
                    "admin_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delegation_grants",
                        to="platform_admin_app.adminsession",
                    ),
                ),
                (
                    "administrator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delegation_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delegation_grants",
                        to="restaurants_app.restaurant",
                    ),
                ),
            ],
            options={
                "db_table": "delegation_grant",
                "ordering": ["-issued_at"],
                "indexes": [
                    models.Index(
                        fields=["administrator", "issued_at"],
                        name="delegation__adminis_b0e5a8_idx",
                    ),
                    models.Index(
                        fields=["restaurant", "issued_at"],
                        name="delegation__restaur_704131_idx",
                    ),
                ],
            },
        ),
    ]
