# Generated by Django 5.2.15 on 2026-07-24 23:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_admin_app", "0005_delegationgrant"),
    ]

    operations = [
        migrations.CreateModel(
            name="DelegatedSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("issued_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ended_reason",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("issued_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("issued_user_agent", models.TextField(blank=True, default="")),
                (
                    "grant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delegated_session",
                        to="platform_admin_app.delegationgrant",
                    ),
                ),
            ],
            options={
                "db_table": "delegated_session",
                "ordering": ["-issued_at"],
            },
        ),
    ]
