# Generated by Django 5.2.15 on 2026-07-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_admin_app", "0006_delegatedsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminloginchallenge",
            name="recovery_only",
            field=models.BooleanField(default=False),
        ),
    ]
