"""
Add ``OwnerInvitation.claim_failed_attempts`` — the Step-2F.2 invitation-level
failed-verification budget.

ADDITIVE ONLY: one ``AddField`` plus its bounding ``AddConstraint``. There is NO
``RunPython``, no backfill, no data repair and no touch of any other table. Every
existing invitation migrates to zero, which is the truthful value: no credential that
predates this column has ever failed an owner-claim verification, because owner-claim
redemption did not exist.

WHAT THE COLUMN IS FOR. ``UserOtp.attempts`` caps guesses per OTP ROW, and
``OtpManager.make_otp`` deletes the previous row and inserts a fresh one with
``attempts=0`` — so re-requesting the second factor resets that budget. Fine for login
UX; not fine for turning a stolen bearer claim token into restaurant authority. This
counter lives on the CREDENTIAL, so it survives OTP re-issuance and can only be reset by
minting a NEW invitation, which is an elevated, reasoned, audited Admin reissue.

WHY ``db_default`` AS WELL AS ``default`` — load-bearing, exactly as in
``users_app/0014``. Django manages defaults in Python: ``AddField`` adds the column WITH
a default and immediately DROPS it, leaving a NOT NULL column with no database default.
Under the expand-only rule a rollback lands OLD CODE ON NEW SCHEMA, and that older
``mint_owner_invitation`` INSERTs an ``owner_invitation`` row without naming this column
— which would be a NOT NULL violation, i.e. Admin restaurant creation and invitation
reissue both broken by a rollback. ``db_default`` keeps a real database-level default so
those inserts succeed and land on zero.

THE BOUND IS A LITERAL. ``claim_failed_attempts <= 5`` matches
``platform_admin_app.models.OWNER_CLAIM_MAX_FAILED_ATTEMPTS``, written out rather than
interpolated so this migration cannot change meaning when a module constant moves.
``platform_admin_app.tests_owner_claim_redemption`` asserts the two agree, so raising the
policy is a deliberate migration rather than a sixth increment that becomes an
``IntegrityError`` in production. It is a BACKSTOP: the redemption service already caps
the increment.

LOCK PROFILE. On PostgreSQL 11+ adding a column with a non-volatile default is
metadata-only — no table rewrite. ``AddConstraint`` validates existing rows, which is
instantaneous here and cannot fail: every row was just set to zero. No index is added —
nothing queries on this column alone; it is only ever read for an already-resolved row.

NOT ADDED, deliberately: no ``claim_locked_at``, no ``status`` column, no last-attempt
timestamp, no attempted-code column, no client-IP column, no claim-session table and no
scheduled cleanup. "Verification locked" is DERIVED from this counter exactly as
"expired" is derived from ``expires_at`` — this repository runs no scheduler, so a
status column nothing maintains would be a lie with a timestamp on it.
"""
# Generated by Django 5.2.16 on 2026-08-27 15:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_admin_app", "0009_restaurantonboarding_ownerinvitation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ownerinvitation",
            name="claim_failed_attempts",
            field=models.PositiveSmallIntegerField(db_default=0, default=0),
        ),
        migrations.AddConstraint(
            model_name="ownerinvitation",
            constraint=models.CheckConstraint(
                condition=models.Q(("claim_failed_attempts__lte", 5)),
                name="owner_invitation_claim_attempts_bounded",
            ),
        ),
    ]
