# Generated by Django 4.2.9 on 2024-02-08 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='country_of_origin',
            new_name='country',
        ),
    ]
