# Generated by Django 4.2.9 on 2025-01-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0006_userotp_msisdn_alter_userotp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='prompt_password_change',
            field=models.BooleanField(default=True),
        ),
    ]
