# Generated by Django 5.2.15 on 2026-07-09 23:23
#
# Adds OTP-hardening columns to user_otps (per-attempt counter, single-use
# marker, per-row salt, stable identifier) and purges any pre-existing rows.
# Existing OTPs are <=5-minute ephemeral and use the old unsalted scheme; a
# clean cutover avoids mixed old/new-scheme rows that could never verify.

from django.db import migrations, models


def purge_existing_otps(apps, schema_editor):
    # Use the historical model so no app-level code / signals are pulled in.
    apps.get_model("users_app", "UserOtp").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("users_app", "0008_backfill_canonical_msisdn"),
    ]

    operations = [
        migrations.AddField(
            model_name="userotp",
            name="attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userotp",
            name="consumed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userotp",
            name="identifier",
            field=models.CharField(db_index=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="userotp",
            name="salt",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.RunPython(purge_existing_otps, migrations.RunPython.noop),
    ]
