# Generated by Django 5.2.15 on 2026-07-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_app", "0009_otp_hardening"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("restaurant_user", "restaurant_user"),
                    ("platform_staff", "platform_staff"),
                ],
                db_index=True,
                default="restaurant_user",
                max_length=32,
            ),
        ),
    ]
