# Generated by Django 5.2.15 on 2026-07-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_app", "0011_flip_admin_account_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                db_index=True, max_length=255, null=True, unique=True
            ),
        ),
    ]
