# Generated by Django 5.2.17 on 2026-09-29 09:07
"""
D11 B2-C: the OTP collection ledger.

EXPAND-ONLY. Two new tables with their own constraints and indexes, and nothing else:
no existing table is altered, no row is written and there is no backfill (a challenge
issued before this ran has no issuance, and a wrong code against it records its origin
as `unrecorded`). Code from before this migration never reads or writes these tables,
so it runs unchanged on the new schema.
"""

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_app", "0014_customer_access_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtpIssuance",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("subject_key", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "destination_key",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("origin", models.CharField(default="unattributed", max_length=32)),
                ("state", models.CharField(default="pending", max_length=16)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "otp_issuances",
                "indexes": [
                    models.Index(fields=["created_at"], name="otp_issuance_created_idx")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "origin__in",
                                (
                                    "password_login",
                                    "reset_initiation",
                                    "owner_claim_challenge",
                                    "login_resend",
                                    "resend_request",
                                    "unattributed",
                                ),
                            )
                        ),
                        name="otp_issuance_origin_vocabulary",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "state__in",
                                ("pending", "accepted", "unknown", "not_dispatched"),
                            )
                        ),
                        name="otp_issuance_state_vocabulary",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("finalized_at__isnull", True), ("state", "pending")
                            ),
                            models.Q(
                                models.Q(("state", "pending"), _negated=True),
                                ("finalized_at__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="otp_issuance_pending_iff_unfinalized",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("subject_key__isnull", True),
                            (
                                "subject_key__regex",
                                "^(u:[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}|p1:[0-9a-f]{64})$",
                            ),
                            _connector="OR",
                        ),
                        name="otp_issuance_subject_is_a_key",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("destination_key__isnull", True),
                            ("destination_key__regex", "^p1:[0-9a-f]{64}$"),
                            _connector="OR",
                        ),
                        name="otp_issuance_destination_is_a_phone_key",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OtpVerificationFailure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "failed_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
                ("subject_key", models.CharField(blank=True, max_length=80, null=True)),
                ("origin", models.CharField(default="unrecorded", max_length=32)),
                ("bound_redemption", models.BooleanField(default=False)),
                ("issuance_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "otp_verification_failures",
                "indexes": [
                    models.Index(fields=["failed_at"], name="otp_failure_failed_idx")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "origin__in",
                                (
                                    "password_login",
                                    "reset_initiation",
                                    "owner_claim_challenge",
                                    "login_resend",
                                    "resend_request",
                                    "unattributed",
                                    "unrecorded",
                                ),
                            )
                        ),
                        name="otp_failure_origin_vocabulary",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("subject_key__isnull", True),
                            (
                                "subject_key__regex",
                                "^(u:[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}|p1:[0-9a-f]{64})$",
                            ),
                            _connector="OR",
                        ),
                        name="otp_failure_subject_is_a_key",
                    ),
                ],
            },
        ),
    ]
