# Generated by Django 4.2.9 on 2024-11-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants_app', '0013_restaurant_order_surcharge_cap_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='first_time_menu_approval_decision',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
