# Generated by Django 4.2.9 on 2024-11-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants_app', '0014_restaurant_first_time_menu_approval_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='allergens',
            field=models.JSONField(default=list),
        ),
    ]
