# Generated by Django 4.2.9 on 2025-03-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants_app', '0016_restaurant_subscription_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menusection',
            options={'ordering': ['listing_position', 'time_created']},
        ),
        migrations.AddField(
            model_name='menusection',
            name='listing_position',
            field=models.IntegerField(default=0),
        ),
    ]
