# Generated by Django 4.2.9 on 2025-03-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants_app', '0018_diningarea_table_dining_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='diningarea',
            name='vacuumed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='vacuumed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menusection',
            name='vacuumed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='vacuumed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurantemployee',
            name='vacuumed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sectiongroup',
            name='vacuumed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='table',
            name='vacuumed',
            field=models.BooleanField(default=False),
        ),
    ]
