# Generated by Django 4.2.9 on 2025-03-31 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants_app', '0019_diningarea_vacuumed_menuitem_vacuumed_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='table',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='table',
            name='str_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('number', 'str_number', 'restaurant')},
        ),
    ]
