# Generated by Django 4.2.9 on 2025-05-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants_app', '0023_remove_table_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
