# Generated by Django 4.2.9 on 2025-05-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants_app', '0024_alter_table_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='diningarea',
            name='eod_last_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='diningarea',
            name='eod_record_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='eod_last_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='eod_record_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='menusection',
            name='eod_last_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='menusection',
            name='eod_record_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='eod_last_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='eod_record_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='eod_restaurant_last_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='eod_restaurant_status',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='restaurantemployee',
            name='eod_last_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantemployee',
            name='eod_record_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sectiongroup',
            name='eod_last_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sectiongroup',
            name='eod_record_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='eod_last_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='eod_record_date',
            field=models.DateField(db_index=True, null=True),
        ),
    ]
