# Generated by Django 4.2.9 on 2025-10-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants_app', '0025_diningarea_eod_last_date_diningarea_eod_record_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
    ]
