# Generated by Django 4.2.9 on 2026-03-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants_app", "0029_menuitem_is_featured_menuitem_is_new_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="menusection",
            name="availability",
            field=models.CharField(
                choices=[("always", "Always"), ("scheduled", "Scheduled")],
                default="always",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="menusection",
            name="schedules",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
