# Generated by Django 4.2.9 on 2026-05-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants_app", "0046_remove_menuitem__legacy_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="age_restricted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="extras_max_selections",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="extras_min_selections",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
