# Generated by Django 4.2.9 on 2026-05-30 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants_app", "0047_menuitem_age_restricted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="menu_item_sort_mode",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("a-z", "A–Z"),
                    ("price-low", "Price low to high"),
                    ("price-high", "Price high to low"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
    ]
