# Generated by Django 5.2.15 on 2026-06-14 18:30

import restaurants_app.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants_app", "0048_restaurant_menu_item_sort_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="accepting_orders",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="cuisine_types",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="landmark",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="receipt_footer",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="socials",
            field=models.JSONField(
                blank=True, default=restaurants_app.models.default_socials
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="tin",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="vat_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("18.00"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="vat_registered",
            field=models.BooleanField(default=False),
        ),
    ]
