# Generated by Django 5.2.15 on 2026-06-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "restaurants_app",
            "0049_restaurant_accepting_orders_restaurant_contact_email_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="tagline",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
