# Generated by Django 5.2.15 on 2026-06-15 00:31

import restaurants_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants_app", "0050_restaurant_tagline"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="opening_hours",
            field=models.JSONField(
                blank=True, default=restaurants_app.models.default_opening_hours
            ),
        ),
    ]
