# Generated by Django 5.2.15 on 2026-07-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants_app", "0053_backfill_role_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="qr_version",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
