# Generated by Django 4.2.9 on 2024-02-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0003_orderitem_last_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prepayment_required',
            field=models.BooleanField(default=False),
        ),
    ]
