# Generated by Django 4.2.9 on 2024-05-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0009_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
