# Generated by Django 4.2.9 on 2024-06-28 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0016_orderitem_option_orderitem_option_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='parent_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_order_item', to='orders_app.orderitem'),
        ),
    ]
