# Generated by Django 4.2.9 on 2024-11-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0018_order_waiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(db_index=True, default='initiated', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(db_index=True, default='pending', max_length=50),
        ),
    ]
