# Generated by Django 4.2.9 on 2025-03-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0019_alter_order_order_status_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vacuumed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vacuumed',
            field=models.BooleanField(default=False),
        ),
    ]
