# Generated by Django 4.2.9 on 2025-10-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0022_alter_orderitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='unit_cost_of_options',
            field=models.FloatField(null=True),
        ),
    ]
