# Generated by Django 4.2.9 on 2026-03-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0025_alter_orderitem_actual_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="selected_modifiers",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
