# Generated by Django 4.2.9 on 2026-06-07 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants_app", "0048_restaurant_menu_item_sort_mode"),
        ("orders_app", "0030_retire_kitchen_tickets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="table",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="table",
                to="restaurants_app.table",
            ),
        ),
    ]
