# Generated by Django 5.2.15 on 2026-06-10 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0031_alter_order_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="order_remarks",
        ),
    ]
