# Generated by Django 5.2.15 on 2026-06-11 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0032_remove_order_order_remarks"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cancellation_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("customer_changed_mind", "Customer changed mind"),
                    ("item_unavailable", "Item unavailable"),
                    ("kitchen_error", "Kitchen error"),
                    ("duplicate", "Duplicate"),
                    ("other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders_cancelled_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
