# Generated by Django 5.2.15 on 2026-06-17 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0033_order_cancellation_reason_order_cancelled_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="block_review",
        ),
        migrations.RemoveField(
            model_name="order",
            name="block_review_reason",
        ),
        migrations.RemoveField(
            model_name="order",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="order",
            name="review",
        ),
        migrations.RemoveField(
            model_name="order",
            name="review_blocked_by",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="block_review",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="block_review_reason",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="review",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="review_blocked_by",
        ),
    ]
