# Generated by Django 5.2.15 on 2026-07-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0034_remove_order_block_review_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_test",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
