"""
D04 — the durable record that a diner's order was accepted.

ONE NEW TABLE AND NOTHING ELSE. No existing table is touched, no column is
added, altered or dropped, there is no `RunPython` and no backfill — and none
is possible: an order accepted before this migration left no record of WHEN it
was accepted or against WHICH quote, and `time_last_updated` is not that fact
(every later kitchen action moves it). An absent row therefore means exactly
"this order was accepted before D04, or has not been accepted", and the
acceptance transition treats the two the same way it treats any other
un-evidenced order: it accepts it once and writes the evidence then.

ROLLBACK. `CreateModel` is the safest shape under the expand-only rule: old
code neither reads nor writes this table, so it runs unchanged against the new
schema, and the rows written in the meantime simply sit unread until the code
returns. Reverting the MIGRATION drops them; reverting only the CODE keeps
them and a re-deploy resumes with the evidence it already wrote.

LOCK COST. Creating a table takes no lock on anything that exists. The
`accepted_at` index is built on an EMPTY table, so unlike `orders_app/0038`'s
index it costs nothing proportional to any row count.
"""
# Generated by Django 5.2.16 on 2026-09-12 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0038_order_request_fingerprint"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderAcceptance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accepted_at", models.DateTimeField(db_index=True)),
                ("quote_ref", models.CharField(max_length=128)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acceptance",
                        to="orders_app.order",
                    ),
                ),
            ],
            options={
                "db_table": "order_acceptances",
            },
        ),
    ]
