"""
D06 — the durable record that an unaccepted quote may never be accepted.

ONE NEW TABLE AND NOTHING ELSE. No existing table is touched, no column is
added, altered or dropped, there is no `RunPython` and no backfill — and none
is possible or wanted: a draft that predates this migration was never closed
under this protocol, so an absent row means exactly "unknown, or not closed".
It never means "accepted" (that is `OrderAcceptance`'s question and its absence
keeps D04's established meaning) and it never means "already safe to replace".

WHY A NEW TABLE RATHER THAN A STATUS. `order_status = 'cancelled'` records a
COMMERCIAL outcome written by the kitchen's cancellation path alongside
`cancelled_at` / `cancelled_by` / `cancellation_reason`. A quote that never
became a kitchen order was not cancelled, and filing it that way would both
corrupt every report reading that axis and — in the dangerous direction — let
an OLD cancelled row with no acceptance evidence be mistaken for a D06 closure.
A table that did not exist before this migration cannot be confused with a
history it was not present for.

ROLLBACK, IN BOTH DIRECTIONS. `CreateModel` is the safest shape under the
expand-only rule for the SCHEMA: old code neither reads nor writes this table,
so it runs unchanged and the rows sit unread until the code returns. The
BEHAVIOURAL direction is the one that needs an operational decision and is
documented with the release plan: old code does not consult closures, so while
it is running a draft this build has permanently closed could still be accepted
by it. That is why a rollback across this change holds rather than simply
reverting, and why the forward fix is preferred.

LOCK COST. Creating a table takes no lock on anything that exists, and the
`closed_at` index is built on an EMPTY table — unlike `orders_app/0038`'s index
it costs nothing proportional to any row count.
"""
# Generated by Django 5.2.17 on 2026-09-17 20:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0040_order_fulfilment_revision"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderQuoteClosure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("closed_at", models.DateTimeField(db_index=True)),
                ("quote_ref", models.CharField(max_length=128)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("quote_expired", "quote_expired"),
                            ("purchase_needs_review", "purchase_needs_review"),
                        ],
                        max_length=32,
                    ),
                ),
                ("policy_version", models.PositiveSmallIntegerField()),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quote_closure",
                        to="orders_app.order",
                    ),
                ),
            ],
            options={
                "db_table": "order_quote_closures",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("reason__in", ("quote_expired", "purchase_needs_review"))
                        ),
                        name="order_quote_closure_reason_vocabulary",
                    )
                ],
            },
        ),
    ]
