# Generated by Django 5.2.17 on 2026-10-07 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0041_order_quote_closure"),
        ("restaurants_app", "0058_table_qr_mode_order_only_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="item",
                to="restaurants_app.menuitem",
            ),
        ),
    ]
