# Generated by Django 4.2.9 on 2026-06-08 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("restaurants_app", "0048_restaurant_menu_item_sort_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportIssue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                ("time_last_updated", models.DateTimeField(auto_now=True)),
                ("time_deleted", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "deletion_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("archived", models.BooleanField(default=False)),
                ("vacuumed", models.BooleanField(default=False)),
                ("eod_last_date", models.DateField(db_index=True, null=True)),
                ("eod_record_date", models.DateField(db_index=True, null=True)),
                (
                    "reference",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("orders_kds", "Orders / KDS"),
                            ("menu", "Menu"),
                            ("tables_qr", "Tables / QR"),
                            ("payments", "Payments"),
                            ("reports", "Reports"),
                            ("account", "Account"),
                            ("bug", "Bug"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "impact",
                    models.CharField(
                        choices=[
                            ("blocking_service", "Blocking service"),
                            ("affecting_service", "Affecting service"),
                            ("non_urgent", "Non-urgent"),
                            ("question", "Question"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In progress"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("contact_phone", models.CharField(blank=True, max_length=50)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                (
                    "preferred_contact_method",
                    models.CharField(blank=True, max_length=30),
                ),
                ("page_url", models.TextField(blank=True)),
                ("user_agent", models.TextField(blank=True)),
                ("internal_notes", models.TextField(blank=True)),
                ("resolution_summary", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_support_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_issues",
                        to="restaurants_app.restaurant",
                    ),
                ),
            ],
            options={
                "db_table": "support_issues",
                "ordering": ["-time_created"],
            },
        ),
    ]
