# Generated by Django 4.2.9 on 2025-05-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysActivityConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('config_name', models.CharField(max_length=255, unique=True)),
                ('config_description', models.TextField(blank=True, null=True)),
                ('config_type', models.CharField(choices=[('boolean', 'Boolean'), ('integer', 'Integer'), ('string', 'String'), ('date', 'DateTime')], max_length=50)),
                ('config_boolean_value', models.BooleanField(default=False)),
                ('config_integer_value', models.IntegerField(default=0)),
                ('config_string_value', models.CharField(blank=True, max_length=255, null=True)),
                ('config_date_value', models.DateField(blank=True)),
                ('eod_last_date', models.DateField(db_index=True, null=True)),
                ('eod_start_time', models.DateTimeField(db_index=True, null=True)),
                ('eod_end_time', models.DateTimeField(db_index=True, null=True)),
                ('eod_current_status', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'sys_activity_config',
            },
        ),
    ]
