# Generated by Django 4.2.9 on 2024-12-25 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants_app', '0016_restaurant_subscription_expiry_date_and_more'),
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceticket',
            name='resolution_date',
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_tickets', to='restaurants_app.restaurant'),
        ),
    ]
