# Generated by Django 4.2.9 on 2025-03-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_remove_serviceticket_resolution_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceticket',
            name='vacuumed',
            field=models.BooleanField(default=False),
        ),
    ]
