# Generated by Django 4.2.9 on 2025-05-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0003_serviceticket_vacuumed'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceticket',
            name='eod_last_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='eod_record_date',
            field=models.DateField(db_index=True, null=True),
        ),
    ]
