# Generated by Django 5.2.16 on 2026-08-23 14:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurants_app", "0057_restaurant_is_test"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RestaurantServiceConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "payment_timing",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pay_first", "pay_first"),
                            ("pay_after", "pay_after"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("payment_timing_set_at", models.DateTimeField(blank=True, null=True)),
                (
                    "payment_collection_mode",
                    models.CharField(
                        blank=True,
                        choices=[("offline", "offline"), ("psp_online", "psp_online")],
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "payment_collection_mode_set_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_collection_mode_set_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_configurations_payment_collection_mode_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_timing_set_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_configurations_payment_timing_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restaurant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_configuration",
                        to="restaurants_app.restaurant",
                    ),
                ),
            ],
            options={
                "db_table": "restaurant_service_configuration",
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("payment_timing__isnull", True),
                            ("payment_timing__in", ["pay_first", "pay_after"]),
                            _connector="OR",
                        ),
                        name="service_configuration_payment_timing_vocabulary",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("payment_collection_mode__isnull", True),
                            ("payment_collection_mode__in", ["offline", "psp_online"]),
                            _connector="OR",
                        ),
                        name="service_configuration_payment_collection_mode_vocabulary",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("payment_timing__isnull", True),
                                ("payment_timing_set_at__isnull", True),
                                ("payment_timing_set_by__isnull", True),
                            ),
                            models.Q(
                                ("payment_timing__isnull", False),
                                ("payment_timing_set_at__isnull", False),
                                ("payment_timing_set_by__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="service_configuration_payment_timing_triple",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("payment_collection_mode__isnull", True),
                                ("payment_collection_mode_set_at__isnull", True),
                                ("payment_collection_mode_set_by__isnull", True),
                            ),
                            models.Q(
                                ("payment_collection_mode__isnull", False),
                                ("payment_collection_mode_set_at__isnull", False),
                                ("payment_collection_mode_set_by__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="service_configuration_payment_collection_mode_triple",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RestaurantSubscriptionTerms",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "recurring_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("currency", models.CharField(max_length=3)),
                (
                    "billing_interval_unit",
                    models.CharField(
                        choices=[
                            ("day", "day"),
                            ("week", "week"),
                            ("month", "month"),
                            ("year", "year"),
                        ],
                        max_length=16,
                    ),
                ),
                ("billing_interval_count", models.PositiveIntegerField()),
                ("effective_from", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscription_terms_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscription_terms",
                        to="restaurants_app.restaurant",
                    ),
                ),
            ],
            options={
                "db_table": "restaurant_subscription_terms",
                "ordering": ["-effective_from"],
                "indexes": [
                    models.Index(
                        fields=["restaurant", "-effective_from"],
                        name="restaurant__restaur_78bfe8_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("ended_at__isnull", True)),
                        fields=("restaurant",),
                        name="one_open_subscription_terms_per_restaurant",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("recurring_amount__gte", 0)),
                        name="subscription_terms_recurring_amount_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "billing_interval_unit__in",
                                ["day", "week", "month", "year"],
                            )
                        ),
                        name="subscription_terms_billing_interval_unit_vocabulary",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("billing_interval_count__gte", 1)),
                        name="subscription_terms_billing_interval_count_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("ended_at__isnull", True),
                            ("ended_at__gte", models.F("effective_from")),
                            _connector="OR",
                        ),
                        name="subscription_terms_ended_after_effective_from",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("currency__regex", "^[A-Z]{3}$")),
                        name="subscription_terms_currency_shape",
                    ),
                ],
            },
        ),
    ]
