"""THE ENVIRONMENT — acquiring exactly the locked files, building a fresh interpreter
environment from ONLY those files, and proving afterwards that what is installed is what
was admitted.

ACQUISITION (network, the only step that is). Each locked file is fetched from the exact
``files.pythonhosted.org`` address the lock names and admitted only if its size and
SHA-256 are the lock's. There is no resolution and no index query: nothing is chosen at
certification time, so a new release, a new wheel for an old version or a changed index
cannot change what is certified. A wheelhouse holding anything but the locked files is
refused.

INSTALLATION (offline). ``python -m venv --without-pip`` — no bundled installer — then the
pinned pip wheel, verified first, installs ITSELF into the environment, and that pip
installs the application closure with ``--isolated --no-index --no-cache-dir
--find-links <wheelhouse> --require-hashes --no-deps --only-binary=:all:``: no index, no
cache, no configuration file or ``PIP_*`` variable, no dependency resolution, no source
build. A file missing from the wheelhouse fails the install; it is never fetched.

RECONCILIATION (offline). The probe, run by the environment's own interpreter, reports
every installed distribution with its RECORD. The installed set must be exactly the locked
set; every Requires-Dist edge, with markers evaluated by that interpreter, must be
satisfied and the closure reachable from the direct inputs must be exactly the locked
application packages (so a locked package the target does not need — a Windows-only
dependency, say — is refused, not silently kept); every file the wheel ships into
site-packages must be on disk with the wheel's own RECORD hash (after the wheel's RECORD is
checked against the wheel's own bytes); nothing else may sit in site-packages unowned;
and ``pip check`` must pass. The result is a PORTABLE inventory — names, versions, wheel
hashes and the digests of the installed files — which does not depend on where the
environment lives, so the certified environment and a reconstruction can be compared.

Console scripts in ``bin/`` are generated by pip with the environment's own path in their
first line, so they are counted and NOT compared; nothing in this closure is executed
through them.
"""

from __future__ import annotations

import base64
import csv
import hashlib
import io
import json
import os
import shutil
import subprocess
import sys
import time
import urllib.error
import urllib.request
import zipfile

from . import lockfile as lf

PROBE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "probe.py")
FETCH_TIMEOUT = 120
INSTALL_TIMEOUT = 900
_GENERATED_DIST_INFO = ("INSTALLER", "REQUESTED", "RECORD")
# Installation and reconciliation never need the network. A dead proxy, with no bypass,
# makes an accidental request fail loudly instead of quietly reaching an index.
OFFLINE = {"https_proxy": "http://127.0.0.1:9", "HTTPS_PROXY": "http://127.0.0.1:9", "http_proxy": "http://127.0.0.1:9",
           "HTTP_PROXY": "http://127.0.0.1:9", "ALL_PROXY": "http://127.0.0.1:9", "no_proxy": "", "NO_PROXY": ""}


def _problem(code, detail):
    return {"code": code, "detail": detail}


def scrubbed_env(extra=None):
    """Nothing that configures pip or the interpreter is inherited.

    ``--isolated`` alone is NOT enough, which a test here found: it ignores ``PIP_*``
    variables and the user's file, but pip still reads ``PIP_CONFIG_FILE``, the global
    ``/etc/pip.conf`` and a ``pip.conf`` inside the environment — any of which can offer a
    ``find-links`` location that satisfies an install the wheelhouse deliberately cannot.
    ``PIP_CONFIG_FILE=/dev/null`` is pip's documented switch for loading no configuration
    file at all."""
    env = {}
    for key, value in os.environ.items():
        upper = key.upper()
        if upper.startswith(("PIP_", "PYTHON")) or key in ("VIRTUAL_ENV", "CONDA_PREFIX", "DJANGO_SETTINGS_MODULE"):
            continue
        env[key] = value
    env["PYTHONNOUSERSITE"] = "1"
    env["PYTHONDONTWRITEBYTECODE"] = "1"
    env["PIP_CONFIG_FILE"] = os.devnull
    env.update(extra or {})
    return env


def run(argv, cwd=None, env=None, timeout=INSTALL_TIMEOUT, stdin=None):
    started = time.monotonic()
    try:
        proc = subprocess.run(argv, cwd=cwd, env=env if env is not None else scrubbed_env(), input=stdin,
                              capture_output=True, text=True, timeout=timeout, check=False)
        status, stdout, stderr = proc.returncode, proc.stdout, proc.stderr
    except subprocess.TimeoutExpired as error:
        status, stdout, stderr = None, error.stdout or "", "timed out after %ss" % timeout
    except OSError as error:
        status, stdout, stderr = None, "", "%s: %s" % (type(error).__name__, error)
    return {"argv": list(argv), "status": status, "stdout": stdout if isinstance(stdout, str) else stdout.decode(),
            "stderr": stderr if isinstance(stderr, str) else stderr.decode(), "seconds": round(time.monotonic() - started, 3)}


def file_sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


# --- acquisition -----------------------------------------------------------------------

def _fetch(url, destination, timeout):
    request = urllib.request.Request(url, headers={"User-Agent": "dinify-backend-release/1"})
    with urllib.request.urlopen(request, timeout=timeout) as response, open(destination, "wb") as out:
        shutil.copyfileobj(response, out, 1 << 20)


def acquire(lock, wheelhouse, fetch=_fetch, timeout=FETCH_TIMEOUT):
    """Download every locked file into an EMPTY ``wheelhouse``, admitting each only on an
    exact size and SHA-256 match. Returns ``(listing, problems)``."""
    if os.path.lexists(wheelhouse) and (not os.path.isdir(wheelhouse) or os.listdir(wheelhouse)):
        return [], [_problem("wheelhouse_not_empty", "%s already holds files; acquisition only fills an empty directory" % wheelhouse)]
    os.makedirs(wheelhouse, exist_ok=True)
    problems = []
    for entry in lf.entries(lock):
        final = os.path.join(wheelhouse, entry["filename"])
        partial = final + ".part"
        for attempt in (1, 2):
            try:
                fetch(entry["url"], partial, timeout)
                break
            except (urllib.error.URLError, OSError, TimeoutError) as error:
                if attempt == 2:
                    problems.append(_problem("acquisition_failed", "%s could not be fetched: %s" % (entry["filename"], error)))
        if not os.path.exists(partial):
            continue
        size, digest = os.path.getsize(partial), file_sha256(partial)
        if (size, digest) != (entry["size"], entry["sha256"]):
            os.remove(partial)
            problems.append(_problem("artifact_mismatch", "%s: fetched %d bytes with sha256 %s; the lock says %d bytes, %s"
                                     % (entry["filename"], size, digest, entry["size"], entry["sha256"])))
            continue
        os.replace(partial, final)
    listing, verify_problems = verify_wheelhouse(lock, wheelhouse)
    return listing, problems + verify_problems


def verify_wheelhouse(lock, wheelhouse):
    """The wheelhouse is EXACTLY the locked files, byte for byte. Returns (listing, problems)."""
    problems, listing = [], []
    expected = {e["filename"]: e for e in lf.entries(lock)}
    try:
        present = sorted(os.listdir(wheelhouse))
    except OSError as error:
        return [], [_problem("wheelhouse_unreadable", "%s: %s" % (wheelhouse, error))]
    for name in present:
        if name not in expected:
            problems.append(_problem("unexpected_artifact", "%s is in the wheelhouse but not in the lock" % name))
    for filename, entry in sorted(expected.items()):
        path = os.path.join(wheelhouse, filename)
        if not os.path.lexists(path):
            problems.append(_problem("missing_artifact", "%s (%s %s) is locked but absent from the wheelhouse"
                                     % (filename, entry["name"], entry["version"])))
            continue
        if os.path.islink(path) or not os.path.isfile(path):
            problems.append(_problem("unsafe_artifact", "%s is not a regular file" % filename))
            continue
        size, digest = os.path.getsize(path), file_sha256(path)
        if (size, digest) != (entry["size"], entry["sha256"]):
            problems.append(_problem("artifact_mismatch", "%s is %d bytes with sha256 %s; the lock says %d bytes, %s"
                                     % (filename, size, digest, entry["size"], entry["sha256"])))
            continue
        listing.append({"filename": filename, "name": entry["name"], "version": entry["version"], "role": entry["role"],
                        "sha256": digest, "size": size})
    return listing, problems


# --- installation ----------------------------------------------------------------------

def venv_python(venv):
    return os.path.join(venv, "bin", "python")


def pip_install_args(wheelhouse, requirements_path):
    return ["install", "--isolated", "--no-input", "--disable-pip-version-check", "--no-cache-dir", "--no-index",
            "--find-links", wheelhouse, "--require-hashes", "--no-deps", "--only-binary=:all:",
            "--root-user-action=ignore", "-r", requirements_path]


def create_environment(lock, wheelhouse, venv, workdir, base_python=None):
    """Build ``venv`` from the wheelhouse alone, offline. Returns ``(report, problems)``."""
    offline = scrubbed_env(OFFLINE)
    base_python = base_python or getattr(sys, "_base_executable", None) or sys.executable
    report = {"venv": venv, "basePython": base_python, "steps": []}
    listing, problems = verify_wheelhouse(lock, wheelhouse)
    report["wheelhouse"] = listing
    if problems:
        return report, problems
    if os.path.lexists(venv):
        return report, [_problem("environment_exists", "%s already exists; a certified environment is always created fresh" % venv)]
    os.makedirs(workdir, exist_ok=True)
    bootstrap = [e for e in lf.entries(lock) if e["role"] == "bootstrap"]
    application = [e for e in lf.entries(lock) if e["role"] == "application"]
    inputs = {}
    for label, selected in (("bootstrap", bootstrap), ("application", application)):
        path = os.path.join(workdir, "%s-requirements.txt" % label)
        text = lf.pip_requirements(selected)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(text)
        inputs[label] = {"path": path, "sha256": lf.sha256(text)}
    report["pipInputs"] = {k: v["sha256"] for k, v in inputs.items()}

    step = run([base_python, "-m", "venv", "--without-pip", venv], env=offline, timeout=300)
    report["steps"].append(dict(step, name="venv --without-pip"))
    if step["status"] != 0:
        return report, [_problem("environment_failed", "the virtual environment could not be created: %s" % step["stderr"][-400:])]
    pip_wheel = os.path.join(wheelhouse, bootstrap[0]["filename"])
    # The pinned installer runs from its own (already verified) wheel and installs itself.
    step = run([venv_python(venv), "-I", os.path.join(pip_wheel, "pip")] + pip_install_args(wheelhouse, inputs["bootstrap"]["path"]), env=offline)
    report["steps"].append(dict(step, name="bootstrap the pinned installer from its wheel"))
    if step["status"] != 0:
        return report, [_problem("bootstrap_failed", "the pinned installer could not install itself (status %s): %s"
                                 % (step["status"], step["stderr"][-600:]))]
    step = run([venv_python(venv), "-I", "-m", "pip"] + pip_install_args(wheelhouse, inputs["application"]["path"]), env=offline)
    report["steps"].append(dict(step, name="install the locked application closure"))
    if step["status"] != 0:
        return report, [_problem("install_failed", "the locked closure could not be installed from the wheelhouse alone "
                                 "(status %s): %s" % (step["status"], step["stderr"][-800:]))]
    return report, []


# --- reconciliation --------------------------------------------------------------------

def probe(python, mode, request):
    step = run([python, "-I", PROBE, mode], env=scrubbed_env(OFFLINE), stdin=json.dumps(request), timeout=300)
    if step["status"] != 0:
        return None, [_problem("probe_failed", "the environment could not be inspected (status %s): %s" % (step["status"], step["stderr"][-600:]))]
    try:
        return json.loads(step["stdout"]), []
    except ValueError as error:
        return None, [_problem("probe_failed", "the probe answer is not JSON (%s)" % error)]


def _record_hash(value):
    """``sha256=<urlsafe base64, unpadded>`` -> hex, or None."""
    if not isinstance(value, str) or not value.startswith("sha256="):
        return None
    raw = value[len("sha256="):]
    try:
        return base64.urlsafe_b64decode(raw + "=" * (-len(raw) % 4)).hex()
    except (ValueError, TypeError):
        return None


def wheel_manifest(path):
    """The files a wheel installs into site-packages, as {relative path: sha256 hex}, after
    checking the wheel's own RECORD against the wheel's own bytes. Returns
    (manifest, outside_site_packages_count, problems)."""
    problems, manifest, outside = [], {}, 0
    name = os.path.basename(path)
    try:
        with zipfile.ZipFile(path) as zf:
            names = zf.namelist()
            if len(names) != len(set(names)):
                return {}, 0, [_problem("wheel_malformed", "%s contains a duplicate member" % name)]
            records = [n for n in names if n.endswith(".dist-info/RECORD") and n.count("/") == 1]
            if len(records) != 1:
                return {}, 0, [_problem("wheel_malformed", "%s does not carry exactly one top-level RECORD" % name)]
            rows = list(csv.reader(io.StringIO(zf.read(records[0]).decode("utf-8"))))
            listed = set()
            for row in rows:
                if not row:
                    continue
                member = row[0]
                listed.add(member)
                if member == records[0]:
                    continue
                expected = _record_hash(row[1] if len(row) > 1 else "")
                if expected is None or member not in names:
                    problems.append(_problem("wheel_malformed", "%s: RECORD row %r has no usable hash or names no member" % (name, member)))
                    continue
                actual = hashlib.sha256(zf.read(member)).hexdigest()
                if actual != expected:
                    problems.append(_problem("wheel_malformed", "%s: %s does not match its own RECORD" % (name, member)))
                    continue
                parts = member.split("/")
                if parts[0].endswith(".data") and len(parts) > 2:
                    if parts[1] in ("purelib", "platlib"):
                        manifest["/".join(parts[2:])] = actual
                    else:
                        outside += 1
                    continue
                manifest[member] = actual
            for member in names:
                if not member.endswith("/") and member not in listed:
                    problems.append(_problem("wheel_malformed", "%s: %s is not listed in its RECORD" % (name, member)))
    except (OSError, zipfile.BadZipFile, UnicodeDecodeError, KeyError) as error:
        return {}, 0, [_problem("wheel_malformed", "%s could not be read: %s" % (name, error))]
    return manifest, outside, problems


def reconcile(lock, wheelhouse, venv, direct):
    """Prove the environment at ``venv`` is exactly the locked closure, installed from the
    wheelhouse files. Returns ``(inventory, problems)``; ``inventory`` is portable."""
    expected = {e["name"]: e for e in lf.entries(lock)}
    answer, problems = probe(venv_python(venv), "inspect", {"wheels": sorted(e["filename"] for e in expected.values()),
                                                            "direct": direct})
    if answer is None:
        return None, problems
    problems = list(answer["problems"])
    markers = answer["markers"]
    wanted = lock["target"]["markers"]
    for key in lf.TARGET_MARKER_KEYS:
        if markers.get(key) != wanted[key]:
            problems.append(_problem("target_mismatch", "marker %s is %r here; the lock was resolved for %r" % (key, markers.get(key), wanted[key])))
    for filename, ok in sorted(answer["wheelSupport"].items()):
        if not ok:
            problems.append(_problem("wheel_incompatible", "%s is not supported by this interpreter" % filename))
    if os.path.realpath(answer["facts"]["prefix"]) != os.path.realpath(venv):
        problems.append(_problem("wrong_environment", "the probe ran in %s, not %s" % (answer["facts"]["prefix"], venv)))

    installed = {d["name"]: d for d in answer["distributions"]}
    for name in sorted(set(installed) - set(expected)):
        problems.append(_problem("unexpected_package", "%s %s is installed but not locked" % (name, installed[name]["version"])))
    for name in sorted(set(expected) - set(installed)):
        problems.append(_problem("missing_package", "%s %s is locked but not installed" % (name, expected[name]["version"])))
    application = {n for n, e in expected.items() if e["role"] == "application"}
    reachable = set(answer["reachable"])
    for name in sorted(application - reachable):
        problems.append(_problem("unexpected_package", "%s is locked but nothing the direct inputs require on this target needs it "
                                 "(a wrong environment marker?)" % name))
    for name in sorted(reachable - application):
        if name in installed:
            problems.append(_problem("unlocked_dependency", "%s is required on this target but is not a locked application package" % name))
    for rel in answer["unowned"]:
        problems.append(_problem("unowned_file", "site-packages/%s belongs to no installed distribution" % rel))

    site = answer["sitePackages"]
    packages = []
    for name in sorted(set(expected) & set(installed)):
        entry, dist = expected[name], installed[name]
        if dist["version"] != entry["version"]:
            problems.append(_problem("version_mismatch", "%s %s is installed; the lock says %s" % (name, dist["version"], entry["version"])))
            continue
        if dist["directUrl"]:
            problems.append(_problem("not_from_wheelhouse", "%s was installed from a direct URL or path, not the wheelhouse" % name))
        if dist["installer"] != "pip":
            problems.append(_problem("unexpected_installer", "%s was installed by %r" % (name, dist["installer"])))
        manifest, outside, wheel_problems = wheel_manifest(os.path.join(wheelhouse, entry["filename"]))
        problems += wheel_problems
        recorded = {os.path.normpath(r[0]) for r in dist["record"]}
        for rel, digest in sorted(manifest.items()):
            path = os.path.join(site, rel)
            if os.path.normpath(rel) not in recorded:
                problems.append(_problem("installed_file_mismatch", "%s: %s is in the wheel but not in the installed RECORD" % (name, rel)))
            elif not os.path.isfile(path) or os.path.islink(path) or file_sha256(path) != digest:
                problems.append(_problem("installed_file_mismatch", "%s: site-packages/%s is not the wheel's file" % (name, rel)))
        for row in dist["record"]:
            rel = os.path.normpath(row[0])
            parts = rel.split(os.sep)
            if rel.startswith(".."):
                continue
            if rel in {os.path.normpath(m) for m in manifest}:
                continue
            if len(parts) == 2 and parts[0] == dist["distInfo"] and parts[1] in _GENERATED_DIST_INFO:
                continue
            if len(parts) >= 2 and parts[-2] == "__pycache__" and rel.endswith(".pyc"):
                continue
            problems.append(_problem("installed_file_mismatch", "%s: the installed RECORD lists %s, which its wheel does not ship" % (name, rel)))
        files = "".join("%s\0%s\n" % (rel, manifest[rel]) for rel in sorted(manifest))
        packages.append({"name": name, "version": entry["version"], "role": entry["role"], "filename": entry["filename"],
                         "wheelSha256": entry["sha256"], "files": len(manifest), "filesSha256": lf.sha256(files),
                         "outsideSitePackages": outside})
    check = run([venv_python(venv), "-I", "-m", "pip", "check", "--isolated", "--disable-pip-version-check"],
                env=scrubbed_env(OFFLINE), timeout=300)
    if check["status"] != 0:
        problems.append(_problem("pip_check_failed", "pip check: %s" % (check["stdout"] + check["stderr"])[-600:]))
    digest = lf.sha256(json.dumps(packages, sort_keys=True, separators=(",", ":")))
    inventory = {"packages": packages, "digest": digest, "installed": len(installed), "pipCheck": check["status"] == 0,
                 "facts": answer["facts"], "markers": {k: markers.get(k) for k in lf.TARGET_MARKER_KEYS}}
    return inventory, problems


def target_problems(lock, facts):
    """The interpreter is the lock's declared target (the markers carry the rest)."""
    target, problems = lock["target"], []
    for key in ("python", "implementation", "platform", "machine"):
        if facts.get(key) != target[key]:
            problems.append(_problem("target_mismatch", "%s is %r here; the lock declares %r" % (key, facts.get(key), target[key])))
    libc = (facts.get("libc") or "").split(" ")
    need = lf._glibc(target["glibc"])
    have = lf._glibc(libc[1]) if len(libc) == 2 and libc[0] == "glibc" else None
    if have is None or need is None or have < need:
        problems.append(_problem("target_mismatch", "libc is %r here; the lock declares glibc %s" % (facts.get("libc"), target["glibc"])))
    return problems


# --- generation (maintainers only; network) --------------------------------------------

def generate(root, workdir, now, base_python=None, fetch=_fetch):
    """Resolve ``requirements.txt`` with the pinned pip and write a new lock body.

    The bootstrap entry (the installer, which is also the generator) is taken from the
    existing lock: changing the installer is itself a reviewed edit. Returns
    ``(lock, problems)``; nothing is written unless there are no problems."""
    with open(os.path.join(root, lf.LOCK_PATH), "rb") as fh:
        current = json.loads(fh.read().decode("utf-8"))
    with open(os.path.join(root, lf.REQUIREMENTS_PATH), "rb") as fh:
        requirements_bytes = fh.read()
    bootstrap = current["bootstrap"][0]
    boot_lock = dict(current, packages=[])
    boot_lock["bootstrap"] = [bootstrap]
    wheelhouse = os.path.join(workdir, "bootstrap")
    _, problems = acquire(boot_lock, wheelhouse, fetch=fetch)
    if problems:
        return None, problems
    venv = os.path.join(workdir, "resolver-venv")
    run([base_python or getattr(sys, "_base_executable", None) or sys.executable, "-m", "venv", "--without-pip", venv], timeout=300)
    boot_req = os.path.join(workdir, "bootstrap-requirements.txt")
    with open(boot_req, "w", encoding="utf-8") as fh:
        fh.write(lf.pip_requirements([bootstrap]))
    step = run([venv_python(venv), "-I", os.path.join(wheelhouse, bootstrap["filename"], "pip")] + pip_install_args(wheelhouse, boot_req))
    if step["status"] != 0:
        return None, [_problem("bootstrap_failed", step["stderr"][-600:])]
    report_path = os.path.join(workdir, "resolution-report.json")
    invocation = ["pip", "install", "--isolated", "--no-input", "--disable-pip-version-check", "--no-cache-dir", "--dry-run",
                  "--ignore-installed", "--only-binary=:all:", "--index-url", lf.INDEX, "--report", "<report>", "-r", lf.REQUIREMENTS_PATH]
    args = [a if a != "<report>" else report_path for a in invocation[1:]]
    args[-1] = os.path.join(root, lf.REQUIREMENTS_PATH)
    step = run([venv_python(venv), "-I", "-m", "pip"] + args)
    if step["status"] != 0:
        return None, [_problem("resolution_failed", step["stderr"][-800:])]
    with open(report_path, "rb") as fh:
        report_bytes = fh.read()
    report = json.loads(report_bytes.decode("utf-8"))
    pins, pin_problems = lf.parse_direct_inputs(requirements_bytes.decode("utf-8"))
    if pin_problems:
        return None, pin_problems
    request = {"direct": sorted(pins), "distributions": [
        {"name": i["metadata"]["name"], "version": i["metadata"]["version"], "requires_dist": i["metadata"].get("requires_dist") or []}
        for i in report["install"]]}
    answer, problems = probe(venv_python(venv), "edges", request)
    if answer is None or answer["problems"]:
        return None, problems + (answer or {}).get("problems", [])
    downloads = os.path.join(workdir, "downloads")
    os.makedirs(downloads, exist_ok=True)
    sizes = {}
    for item in report["install"]:
        info = item["download_info"]
        filename = os.path.basename(info["url"])
        path = os.path.join(downloads, filename)
        fetch(info["url"], path, FETCH_TIMEOUT)
        if file_sha256(path) != info["archive_info"]["hashes"]["sha256"]:
            return None, [_problem("artifact_mismatch", "%s did not match the resolver's recorded hash" % filename)]
        sizes[filename] = os.path.getsize(path)
    facts = answer["facts"]
    libc = (facts.get("libc") or "").split(" ")
    target = {"python": facts["python"], "implementation": facts["implementation"], "platform": facts["platform"],
              "machine": facts["machine"], "glibc": libc[1] if len(libc) == 2 else None}
    return lf.from_report(report, requirements_bytes, bootstrap, invocation, now, report_bytes, answer["requiredBy"], sizes, target)
