# Generated by Django 5.2.15 on 2026-06-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="resolution_note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
