# Generated by Django 5.2.15 on 2026-06-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews_app", "0002_review_resolution_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
