# Generated by Django 4.2.9 on 2024-03-18 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import finance_app.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants_app', '0006_menuitem_discount_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders_app', '0005_orderitem_cost_of_options_orderitem_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DinifyAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_last_updated', models.DateTimeField(auto_now=True)),
                ('time_deleted', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deletion_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('account_currency', models.CharField(db_index=True, default='UGX', max_length=10)),
                ('account_type', models.CharField(db_index=True, max_length=255, validators=[finance_app.models.validate_account_type])),
                ('account_status', models.CharField(default='active', max_length=20, validators=[finance_app.models.validate_account_status])),
                ('actual_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('cumulative_in', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('cumulative_out', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('cumulative_in_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('cumulative_out_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('cumulative_refunds', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('cumulative_disbursements', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants_app.restaurant')),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='DinifyTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_last_updated', models.DateTimeField(auto_now=True)),
                ('time_deleted', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deletion_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_type', models.CharField(db_index=True, max_length=255, validators=[finance_app.models.validate_transaction_type])),
                ('transaction_status', models.CharField(db_index=True, max_length=255, validators=[finance_app.models.validate_transaction_status])),
                ('transaction_platform', models.CharField(db_index=True, max_length=255, validators=[finance_app.models.validate_transaction_platform])),
                ('transaction_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('transaction_collected_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('msisdn', models.CharField(blank=True, max_length=255, null=True)),
                ('aggregator', models.CharField(blank=True, max_length=255, null=True)),
                ('aggregator_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_mode', models.CharField(blank=True, max_length=255, null=True, validators=[finance_app.models.validate_payment_mode])),
                ('aggregator_status', models.CharField(blank=True, max_length=255, null=True)),
                ('account_balances', models.JSONField(default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance_app.dinifyaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders_app.order')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants_app.restaurant')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
