# Generated by Django 4.2.9 on 2024-05-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0004_rename_actual_balance_dinifyaccount_momo_actual_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinifytransaction',
            name='payment_form',
            field=models.CharField(default='full', max_length=20),
        ),
    ]
