# Generated by Django 4.2.9 on 2024-08-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0006_dinifytransaction_manual_payment_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinifytransaction',
            name='aggregator_misc_details',
            field=models.JSONField(default=dict),
        ),
    ]
