# Generated by Django 4.2.9 on 2024-08-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0007_dinifytransaction_aggregator_misc_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinifytransaction',
            name='tip_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
    ]
