# Generated by Django 4.2.9 on 2024-09-02 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0009_dinifyaccount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinifytransaction',
            name='source_order_payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ref_source_order_payment', to='finance_app.dinifytransaction'),
        ),
        migrations.AlterField(
            model_name='dinifytransaction',
            name='revenue_initiation_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ref_revenue_initiation_transaction', to='finance_app.dinifytransaction'),
        ),
    ]
