# Generated by Django 4.2.9 on 2024-12-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0012_remove_dinifytransaction_revenue_collection_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinifytransaction',
            name='amount_in',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
        migrations.AddField(
            model_name='dinifytransaction',
            name='amount_out',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
    ]
