# Generated by Django 4.2.9 on 2024-12-13 17:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants_app', '0016_restaurant_subscription_expiry_date_and_more'),
        ('finance_app', '0017_alter_dinifytransaction_aggregator'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bankaccountrecord',
            unique_together={('restaurant', 'user', 'bank_name', 'account_number')},
        ),
        migrations.AlterModelTable(
            name='bankaccountrecord',
            table='bank_account_records',
        ),
    ]
