# Generated by Django 4.2.9 on 2024-12-13 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants_app', '0016_restaurant_subscription_expiry_date_and_more'),
        ('finance_app', '0018_alter_bankaccountrecord_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccountrecord',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants_app.restaurant'),
        ),
        migrations.AlterField(
            model_name='bankaccountrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
