# Generated by Django 4.2.9 on 2025-03-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0021_alter_bankaccountrecord_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccountrecord',
            name='vacuumed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dinifyaccount',
            name='vacuumed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dinifytransaction',
            name='vacuumed',
            field=models.BooleanField(default=False),
        ),
    ]
