# Generated by Django 4.2.9 on 2025-05-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0022_bankaccountrecord_vacuumed_dinifyaccount_vacuumed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccountrecord',
            name='eod_last_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='bankaccountrecord',
            name='eod_record_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='dinifyaccount',
            name='eod_last_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='dinifyaccount',
            name='eod_record_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='dinifytransaction',
            name='eod_last_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='dinifytransaction',
            name='eod_record_date',
            field=models.DateField(db_index=True, null=True),
        ),
    ]
