# Generated by Django 5.2.15 on 2026-06-18 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance_app", "0023_bankaccountrecord_eod_last_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dinifyaccount",
            name="card_actual_balance",
        ),
        migrations.RemoveField(
            model_name="dinifyaccount",
            name="card_available_balance",
        ),
        migrations.RemoveField(
            model_name="dinifyaccount",
            name="card_cumulative_disbursements",
        ),
        migrations.RemoveField(
            model_name="dinifyaccount",
            name="card_cumulative_in",
        ),
        migrations.RemoveField(
            model_name="dinifyaccount",
            name="card_cumulative_in_charges",
        ),
        migrations.RemoveField(
            model_name="dinifyaccount",
            name="card_cumulative_out",
        ),
        migrations.RemoveField(
            model_name="dinifyaccount",
            name="card_cumulative_out_charges",
        ),
        migrations.RemoveField(
            model_name="dinifyaccount",
            name="card_cumulative_refunds",
        ),
        migrations.RemoveField(
            model_name="dinifyaccount",
            name="cash_actual_balance",
        ),
        migrations.RemoveField(
            model_name="dinifyaccount",
            name="cash_available_balance",
        ),
        migrations.RemoveField(
            model_name="dinifyaccount",
            name="cash_cumulative_disbursements",
        ),
        migrations.RemoveField(
            model_name="dinifyaccount",
            name="cash_cumulative_in",
        ),
        migrations.RemoveField(
            model_name="dinifyaccount",
            name="cash_cumulative_in_charges",
        ),
        migrations.RemoveField(
            model_name="dinifyaccount",
            name="cash_cumulative_out",
        ),
        migrations.RemoveField(
            model_name="dinifyaccount",
            name="cash_cumulative_out_charges",
        ),
        migrations.RemoveField(
            model_name="dinifyaccount",
            name="cash_cumulative_refunds",
        ),
        migrations.RemoveField(
            model_name="dinifyaccount",
            name="momo_actual_balance",
        ),
        migrations.RemoveField(
            model_name="dinifyaccount",
            name="momo_available_balance",
        ),
        migrations.RemoveField(
            model_name="dinifyaccount",
            name="momo_cumulative_disbursements",
        ),
        migrations.RemoveField(
            model_name="dinifyaccount",
            name="momo_cumulative_in",
        ),
        migrations.RemoveField(
            model_name="dinifyaccount",
            name="momo_cumulative_in_charges",
        ),
        migrations.RemoveField(
            model_name="dinifyaccount",
            name="momo_cumulative_out",
        ),
        migrations.RemoveField(
            model_name="dinifyaccount",
            name="momo_cumulative_out_charges",
        ),
        migrations.RemoveField(
            model_name="dinifyaccount",
            name="momo_cumulative_refunds",
        ),
    ]
