# Generated by Django 5.2.15 on 2026-06-18 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance_app", "0024_remove_dinifyaccount_card_actual_balance_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dinifytransaction",
            name="account_balances",
        ),
        migrations.RemoveField(
            model_name="dinifytransaction",
            name="amount_out",
        ),
        migrations.RemoveField(
            model_name="dinifytransaction",
            name="customer_balance",
        ),
        migrations.RemoveField(
            model_name="dinifytransaction",
            name="gross_amount_paid",
        ),
        migrations.RemoveField(
            model_name="dinifytransaction",
            name="parent_transaction",
        ),
        migrations.RemoveField(
            model_name="dinifytransaction",
            name="processed",
        ),
        migrations.RemoveField(
            model_name="dinifytransaction",
            name="revenue_collected",
        ),
        migrations.RemoveField(
            model_name="dinifytransaction",
            name="transaction_notes",
        ),
    ]
