# Generated by Django 5.2.15 on 2026-06-18 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance_app", "0025_remove_dinifytransaction_account_balances_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dinifytransaction",
            name="account",
        ),
        migrations.DeleteModel(
            name="DinifyAccount",
        ),
    ]
