# Generated by Django 5.2.15 on 2026-06-19 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance_app", "0026_remove_dinifytransaction_account_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BankAccountRecord",
        ),
    ]
