# Generated by Django 5.2.15 on 2026-06-19 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance_app", "0027_delete_bankaccountrecord"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dinifytransaction",
            name="tip_amount",
        ),
    ]
