"""The capability levels this server PUBLISHES, as a contract a client can check.

THE PROBLEM THIS EXISTS TO CLOSE. Dinify-Frontend's release gate refuses to publish
a client that needs a higher capability level than the backend it will run beside —
``checkout_protocol``, ``quote_protocol``, ``kitchen_protocol`` — and checks the
quote-policy version the client understands. Until now the levels it compared
against were INTEGERS TYPED INTO THE FRONTEND'S OWN POLICY, read by a person from
this repository's source on the day the policy was written. A comparison against a
local assertion checks the assertion, not the server: nothing tied those integers
to the revision of this repository they claimed to describe.

WHAT CLOSES IT. The same shape ``checkout_limits`` established for the D01
ceilings: this module derives the published set from the production constants the
wire actually emits — never by typing the numbers a second time — and a committed
export (``published_capabilities.contract.json``) is asserted against it
UNCONDITIONALLY by ``orders_app/tests_published_capabilities.py``. The frontend's
peer-receipt producer reads that committed file AT AN EXACT SELECTED COMMIT of this
repository, so what the gate compares is what this source said at that revision.

WHAT IT DOES NOT DO. It enforces nothing and exposes nothing at runtime: there is no
endpoint, no header and no new field on any response. It states four constants in a
form another repository can read from git. Whether a particular revision is the one
SERVING is a separate question this module cannot answer — that is B3's runtime
identity, and until it exists the frontend gate refuses on it by name.

The canonical form is the one ``checkout_limits`` uses —
``json.dumps(values, sort_keys=True, separators=(',', ':'))`` — and keys beginning
``_`` are provenance notes that never enter it.
"""
import hashlib
import json
import pathlib

from orders_app.controllers.services.checkout_protocol import CHECKOUT_PROTOCOL
from orders_app.controllers.services.kitchen_transition import KITCHEN_PROTOCOL
from orders_app.controllers.services.quote_policy import QUOTE_POLICY_VERSION
from orders_app.controllers.services.quote_protocol import QUOTE_PROTOCOL

#: The committed export. Repository-relative, beside this module.
CONTRACT_FILE = pathlib.Path(__file__).with_name('published_capabilities.contract.json')

#: Wire name -> the production constant that emits it, and where. The wire name is
#: the key a client reads off a response, which is what a release gate compares a
#: client's requirement against. The module path is recorded so a reader of the
#: export can find the constant without searching.
PUBLISHED = (
    ('checkout_protocol', 'orders_app/controllers/services/checkout_protocol.py', CHECKOUT_PROTOCOL),
    ('quote_protocol', 'orders_app/controllers/services/quote_protocol.py', QUOTE_PROTOCOL),
    ('kitchen_protocol', 'orders_app/controllers/services/kitchen_transition.py', KITCHEN_PROTOCOL),
    ('quote_policy_version', 'orders_app/controllers/services/quote_policy.py', QUOTE_POLICY_VERSION),
)


def published_values():
    """The published levels, read from the constants the wire emits."""
    return {name: value for name, _source, value in PUBLISHED}


def _values_only(values):
    """Drop provenance notes, whatever mapping a caller supplies (see checkout_limits)."""
    return {k: v for k, v in values.items() if not str(k).startswith('_')}


def canonical_json(values=None):
    """The exact text a peer digests."""
    return json.dumps(
        published_values() if values is None else _values_only(values),
        sort_keys=True,
        separators=(',', ':'),
    )


def contract_digest(values=None):
    """``sha256:<hex>`` over the canonical text."""
    return 'sha256:' + hashlib.sha256(canonical_json(values).encode('utf-8')).hexdigest()


def committed_export():
    """The committed JSON, with provenance notes stripped."""
    return _values_only(json.loads(CONTRACT_FILE.read_text()))


def export_text():
    """The exact bytes ``published_capabilities.contract.json`` should contain."""
    body = {
        '_sources': {name: source for name, source, _value in PUBLISHED},
        '_note': (
            'Source-authoritative export of the capability levels this server '
            'publishes. Generated by `manage.py export_published_capabilities`; '
            'asserted against the live constants by '
            'orders_app/tests_published_capabilities.py, unconditionally. A '
            'statement about this SOURCE at this revision, not about any deployment.'
        ),
        **published_values(),
    }
    return json.dumps(body, indent=2) + '\n'
